# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9af84e1edf166d0a8a32f3af9fe265bc63945304211cb7036dc88f18d8e2ecfa2a41cc6bc5dfa2b2769ff391529199498f2297d2a38d6630aabfb703787634a1

test:
  secret_key_base: 4b95783f56334248e01e4557a29efc53410498cdeca0f3a11b9f0ad47c3c8cf408f873b0715718a0d65dbfdce1ab0174bf4eb6723af3564009471465c35e02c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
